spring.application.name=school-portal
jwt.secret=5c88aa9080bab9e5a4ab28f0707f0176c8d30f1ede8ac4445852d97add6fe18f
jwt.expiration=3600000
spring.jackson.property-naming-strategy=SNAKE_CASE
cors.allowed-origins=http://localhost:4321

# --- Database Connection (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/schoolportal
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate Settings ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# --- Spring Session Configuration ---
spring.session.jdbc.initialize-schema=always