CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE SCHEMA IF NOT EXISTS school;

-- =============================================================================
-- ENUM TYPES
-- =============================================================================
CREATE TYPE school.account_status AS 
        ENUM ('Active','Inactive');
CREATE TYPE school.auth_provider_enum AS
        ENUM ('Local','Microsoft');
CREATE TYPE school.student_status_enum AS
        ENUM ('Admitted','Enrolled','LeaveOfAbsence','Dropped','Graduated');
CREATE TYPE school.education_level_enum AS
        ENUM ('Undergraduate','Graduate');
CREATE TYPE school.student_type_enum AS 
        ENUM ('Regular','Irregular');
CREATE TYPE school.professor_status_enum AS
        ENUM ('Active','OnLeave','Resigned','Terminated');
CREATE TYPE school.employee_type_enum AS
        ENUM ('FullTime','PartTime');
CREATE TYPE school.delivery_mode_enum AS
        ENUM ('FaceToFace', 'Online', 'Hybrid');
-- =============================================================================
-- ENTITY TABLE DEFINITIONS
-- =============================================================================
-- I. USER MANAGEMENT
--    1. Accounts ✓
CREATE TABLE school.accounts (
        account_id                        UUID                          NOT NULL DEFAULT gen_random_uuid()
        , status                          school.account_status         NOT NULL DEFAULT 'Active'
        , email                           VARCHAR(255)                  NOT NULL UNIQUE
        , password_hash                   VARCHAR(255)                      NULL
        , auth_provider                   school.auth_provider_enum     NOT NULL DEFAULT 'Local'
        , auth_provider_id                VARCHAR(255)                      NULL
        , created_at                      TIMESTAMP                     NOT NULL DEFAULT CURRENT_TIMESTAMP
        , PRIMARY KEY (account_id)
);

--    2. User Profiles ✓
CREATE TABLE school.user_profiles (
        account_id                        UUID                          NOT NULL
        , first_name                      VARCHAR(50)                   NOT NULL
        , middle_name                     VARCHAR(50)                       NULL
        , last_name                       VARCHAR(50)                   NOT NULL
        , PRIMARY KEY (account_id)
);

--    3. Roles ✓
CREATE TABLE school.roles (
        role_no                           BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
        , role_name                       VARCHAR(20)                   NOT NULL UNIQUE
        , PRIMARY KEY (role_no)
);

--    4. Account_Roles ◆ ✓
CREATE TABLE school.account_roles (
        account_id                        UUID                          NOT NULL
        , role_no                         BIGINT                        NOT NULL
        , PRIMARY KEY (account_id, role_no)
);

--    5. Students ✓
CREATE TABLE school.students (
        account_id                        UUID                          NOT NULL
        , student_no                      BIGINT                        NOT NULL
        , student_status                  school.student_status_enum    NOT NULL DEFAULT 'Admitted'
        , education_level                 school.education_level_enum   NOT NULL DEFAULT 'Undergraduate'
        , student_type                    school.student_type_enum      NOT NULL DEFAULT 'Regular'
        , year_level                      BIGINT                        NOT NULL DEFAULT 1
        , student_admitted_at             TIMESTAMP                     NOT NULL DEFAULT CURRENT_TIMESTAMP
        , PRIMARY KEY (account_id)
);

--    6. Professors ✓
CREATE TABLE school.professors (
        account_id                        UUID                          NOT NULL
        , professor_id                    VARCHAR(10)                   NOT NULL
        , professor_status                school.professor_status_enum  NOT NULL DEFAULT 'Active'
        , employee_type                   school.employee_type_enum     NOT NULL
        , prof_hired_at                   TIMESTAMP                     NOT NULL DEFAULT CURRENT_TIMESTAMP
        , PRIMARY KEY (account_id)
);

-- II. ACADEMIC STRUCTURE
--    1. Colleges ✓
CREATE TABLE school.colleges (
        college_code                      VARCHAR(10)                   NOT NULL
        , college_name                    VARCHAR(100)                  NOT NULL
        , PRIMARY KEY (college_code)
);

--    2. Courses ✓
CREATE TABLE school.courses (
        course_code                       VARCHAR(10)                   NOT NULL
        , course_name                     VARCHAR(100)                  NOT NULL
        , course_tier                     school.education_level_enum   NOT NULL
        , college_code                    VARCHAR(10)                   NOT NULL
        , PRIMARY KEY (course_code)
);

--    3. Blocks ✓
CREATE TABLE school.blocks (
        block_no                          BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
        , course_code                     VARCHAR(10)                   NOT NULL
        , year_level                      BIGINT                        NOT NULL
        , block_number                    BIGINT                        NOT NULL
        , PRIMARY KEY (block_no)
);

--    4. Course_Subjects ◆ ✓
CREATE TABLE school.course_subjects (
        course_code                       VARCHAR(10)                   NOT NULL
        , subject_code                    VARCHAR(10)                   NOT NULL
        , PRIMARY KEY (course_code, subject_code)
);

-- III. ACADEMIC OFFERINGS
--    1. Subjects ✓
CREATE TABLE school.subjects (
        subject_code                      VARCHAR(10)                   NOT NULL
        , subject_name                    VARCHAR(100)                  NOT NULL
        , lec_units                       BIGINT                        NOT NULL DEFAULT  0
        , lab_units                       BIGINT                        NOT NULL DEFAULT  0
        , PRIMARY KEY (subject_code)
);

--    2. Subject_Prereqs ◆ ✓
CREATE TABLE school.subject_prereqs (
        subject_code                      VARCHAR(10)                   NOT NULL
        , prereq_subject_code             VARCHAR(10)                   NOT NULL
        , PRIMARY KEY (subject_code, prereq_subject_code)
);

--    3. Sections ✓
CREATE TABLE school.sections (
        section_no                        BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
        , available_slots                 BIGINT                        NOT NULL DEFAULT 40
        , version                         BIGINT                        NOT NULL DEFAULT  0
        , delivery_mode                   school.delivery_mode_enum     NOT NULL
        , subject_code                    VARCHAR(10)                   NOT NULL
        , professor_id                    VARCHAR(10)                   NOT NULL
        , academic_term_id                BIGINT                        NOT NULL
        , PRIMARY KEY (section_no)
);

--    4. Section_Blocks ◆ ✓
CREATE TABLE school.section_blocks (
        section_id                        VARCHAR(10)                   NOT NULL
        , block_no                        BIGINT                        NOT NULL
        , PRIMARY KEY (section_id, block_no)
);

-- IV. ENROLLMENT
--    1. Enrollments ✓
CREATE TABLE school.enrollments (
        enrollment_no                     BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
        , enrolled_at                     DATE                          NOT NULL
        , created_at                      DATE                          NOT NULL
        , status                          CHAR                          NOT NULL
        , account_id                      UUID                          NOT NULL
        , academic_term_no                BIGINT                        NOT NULL
        , PRIMARY KEY (enrollment_no)
);

--    2. Enrolled_Sections ◆ ✓
CREATE TABLE school.enrollment_sections (
        enrollment_no                     BIGINT                        NOT NULL
        , section_no                      DATE                          NOT NULL
        , subject_status                  CHAR                          NOT NULL
        , PRIMARY KEY (enrollment_no, section_no)
);

-- V. TIME & LOCATION
--    1. Schedules ✓
CREATE TABLE school.schedules (
        schedule_no                       BIGINT                        NOT NULL
        , day_of_week                     CHAR                          NOT NULL
        , start_time                      VARCHAR(5)                    NOT NULL
        , end_time                        VARCHAR(5)                    NOT NULL
        , section_no                      BIGINT                        NOT NULL
        , room_no                         BIGINT                        NOT NULL
        , PRIMARY KEY (schedule_no)
);

--    2. Service_Histories
--    3. School_Years ✓
CREATE TABLE school.school_years (
        sy_no                             BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
        , sy_name                         VARCHAR(50)                   NOT NULL
        , sy_start_date                   DATE                          NOT NULL
        , sy_end_date                     DATE                          NOT NULL
        , PRIMARY KEY (sy_no)
);

--    4. Term_Types ✓
CREATE TABLE school.term_types (
        term_type_id                      VARCHAR(2)                    NOT NULL
        , term_description                VARCHAR(50)                   NOT NULL
        , PRIMARY KEY (term_type_id)
);

--    5. Academic_Terms ✓
CREATE TABLE school.academic_terms (
        academic_term_no                  BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
        , term_name                       VARCHAR(50)                   NOT NULL
        , term_start_date                 DATE                          NOT NULL
        , term_end_date                   DATE                          NOT NULL
        , enrollment_start                DATE                          NOT NULL
        , enrollment_end                  DATE                          NOT NULL
        , sy_no                           BIGINT                        NOT NULL
        , term_type_id                    VARCHAR(2)                    NOT NULL
        , PRIMARY KEY (academic_term_no)
);

--    6. Buildings
--    7. Rooms ✓

-- VI. GRADING
--    1. Grade Components
--    2. Grades

-- =============================================================================
-- DEFAULT INSERTS
-- =============================================================================
-- I. USER MANAGEMENT
--    Roles
INSERT INTO school.roles (role_name) VALUES ('student');
INSERT INTO school.roles (role_name) VALUES ('professor');
INSERT INTO school.roles (role_name) VALUES ('admin');

-- =============================================================================
-- CONSTRAINTS
-- =============================================================================
-- I. USER MANAGEMENT
--    1. Accounts
ALTER TABLE school.accounts
        ADD CONSTRAINT acc_email_fmt_ck
                CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
        ADD CONSTRAINT email_lower_ck 
                CHECK (email = LOWER(email));

--    2. User Profiles
ALTER TABLE school.user_profiles
        ADD CONSTRAINT fk_user_profiles_account
                FOREIGN KEY (account_id)
                REFERENCES school.accounts(account_id)
                ON DELETE CASCADE;

--    3. Roles
ALTER TABLE school.roles
        ADD CONSTRAINT uq_roles_role_name
                UNIQUE (role_name);

--    4. Account Roles
ALTER TABLE school.account_roles
        ADD CONSTRAINT fk_account_roles_account
                FOREIGN KEY (account_id)
                REFERENCES school.accounts(account_id)
                ON DELETE CASCADE,
        ADD CONSTRAINT fk_account_roles_role
                FOREIGN KEY (role_no)
                REFERENCES school.roles(role_no);

--    5. Students
ALTER TABLE school.students
        ADD CONSTRAINT fk_students_account
                FOREIGN KEY (account_id)
                REFERENCES school.accounts(account_id)
                ON DELETE CASCADE,
        ADD CONSTRAINT uq_students_student_no
                UNIQUE (student_no);

--    6. Professors
ALTER TABLE school.professors
        ADD CONSTRAINT fk_professors_account
                FOREIGN KEY (account_id)
                REFERENCES school.accounts(account_id)
                ON DELETE CASCADE,
        ADD CONSTRAINT uq_professors_professor_id
                UNIQUE (professor_id);

-- II. ACADEMIC STRUCTURE
--    1. Colleges ✓
--    2. Courses ✓
--    3. Blocks ✓
--    4. Course_Subjects ◆ ✓
-- III. ACADEMIC OFFERINGS
--    1. Subjects ✓
--    2. Subject_Prereqs ◆ ✓
--    3. Sections ✓
--    4. Section_Blocks ✓
-- IV. ENROLLMENT
--    1. Enrollments
--    2. Enrolled_Sections
-- V. TIME & LOCATION
--    1. Schedules ✓
--    2. Service_Histories
--    3. School_Years ✓
--    4. Term_Types ✓
--    5. Academic_Terms ✓
--    6. Buildings
--    7. Rooms ✓
-- =============================================================================
-- VIEW TABLE DEFINITIONS
-- =============================================================================
-- Login View
CREATE OR REPLACE VIEW school.vwlogin AS
SELECT
    a.account_id,
    a.email,
    a.password_hash,
    a.status,
    ar.role_no
FROM
    school.accounts a
JOIN
    school.account_roles ar
        ON a.account_id = ar.account_id;

-- Test Admin
WITH acc AS (
    INSERT INTO school.accounts (email, password_hash)
        VALUES ('admin@example.com', '$2a$10$urO3DSWyBBPEYuh8GQzXPu4KFlksPbWsc.pnRWY6Z0vTA.jsMWTkO')
        RETURNING account_id
),
     profile AS (
         INSERT INTO school.user_profiles (account_id, first_name, last_name)
             SELECT account_id, 'Admin', 'User'
             FROM acc
             RETURNING account_id
     )
INSERT INTO school.account_roles (account_id, role_no)
SELECT account_id, 3  -- ADMIN
FROM profile;
