-- =============================================================================
-- DATABASE INITIALIZATION SCRIPT
-- =============================================================================
-- Features: pgcrypto, btree_gist (for exclusionary constraints)
-- Styling: Comma-first, Vertically Aligned
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE SCHEMA IF NOT EXISTS school;

-- =============================================================================
-- ENUM TYPES
-- =============================================================================
CREATE TYPE school.account_status AS
    ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE school.auth_provider_enum AS
    ENUM ('LOCAL', 'MICROSOFT');
CREATE TYPE school.student_status_enum AS
    ENUM ('ADMITTED', 'ENROLLED', 'LEAVE_OF_ABSENCE', 'DROPPED', 'GRADUATED');
CREATE TYPE school.education_level_enum AS
    ENUM ('UNDERGRADUATE', 'GRADUATE');
CREATE TYPE school.student_type_enum AS
    ENUM ('REGULAR', 'IRREGULAR');
CREATE TYPE school.professor_status_enum AS
    ENUM ('ACTIVE', 'ON_LEAVE', 'RESIGNED', 'TERMINATED');
CREATE TYPE school.employee_type_enum AS
    ENUM ('FULL_TIME', 'PART_TIME');
CREATE TYPE school.delivery_mode_enum AS
    ENUM ('FACE_TO_FACE', 'ONLINE', 'HYBRID');
CREATE TYPE school.subject_status_enum AS
    ENUM ('ENROLLED', 'DROPPED', 'CREDITED');
CREATE TYPE school.enrollment_status_enum AS
    ENUM ('DRAFT', 'ENROLLED', 'DROPPED');
CREATE TYPE school.day_name_enum AS
    ENUM ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY');
CREATE TYPE school.service_status_enum AS
    ENUM ('PROBATIONARY', 'PERMANENT', 'CONTRACTUAL', 'SUBSTITUTE', 'CONSULTANT');
CREATE TYPE school.room_type_enum AS
    ENUM ('CLASSROOM', 'LAB', 'AUDITORIUM', 'ONLINE', 'FIELD');

-- =============================================================================
-- ENTITY TABLE DEFINITIONS
-- =============================================================================

-- I. USER MANAGEMENT
--    1. Accounts
CREATE TABLE school.accounts (
    account_id                        UUID                          NOT NULL DEFAULT gen_random_uuid()
    , status                          school.account_status         NOT NULL DEFAULT 'ACTIVE'
    , email                           VARCHAR(255)                  NOT NULL UNIQUE
    , password_hash                   VARCHAR(255)                      NULL
    , auth_provider                   school.auth_provider_enum     NOT NULL DEFAULT 'LOCAL'
    , auth_provider_id                VARCHAR(255)                      NULL
    , created_at                      TIMESTAMPTZ                   NOT NULL DEFAULT NOW()
    , PRIMARY KEY (account_id)
);

--    2. User Profiles
CREATE TABLE school.user_profiles (
    account_id                        UUID                          NOT NULL
    , first_name                      VARCHAR(50)                   NOT NULL
    , middle_name                     VARCHAR(50)                       NULL
    , last_name                       VARCHAR(50)                   NOT NULL
    , PRIMARY KEY (account_id)
);

--    3. Roles
CREATE TABLE school.roles (
    role_no                           BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , role_name                       VARCHAR(20)                   NOT NULL UNIQUE
    , PRIMARY KEY (role_no)
);

--    4. Account Roles
CREATE TABLE school.account_roles (
    account_id                        UUID                          NOT NULL
    , role_no                         BIGINT                        NOT NULL
    , PRIMARY KEY (account_id, role_no)
);

--    5. Students
CREATE TABLE school.students (
    account_id                        UUID                          NOT NULL
    , student_no                      BIGINT                        NOT NULL
    , student_status                  school.student_status_enum    NOT NULL DEFAULT 'ADMITTED'
    , education_level                 school.education_level_enum   NOT NULL DEFAULT 'UNDERGRADUATE'
    , student_type                    school.student_type_enum      NOT NULL DEFAULT 'REGULAR'
    , year_level                      BIGINT                        NOT NULL DEFAULT 1
    , student_admitted_at             TIMESTAMPTZ                   NOT NULL DEFAULT NOW()
    , PRIMARY KEY (account_id)
);

--    6. Professors
CREATE TABLE school.professors (
    account_id                        UUID                          NOT NULL
    , professor_id                    VARCHAR(10)                   NOT NULL
    , professor_status                school.professor_status_enum  NOT NULL DEFAULT 'ACTIVE'
    , employee_type                   school.employee_type_enum     NOT NULL
    , prof_hired_at                   TIMESTAMPTZ                   NOT NULL DEFAULT NOW()
    , PRIMARY KEY (account_id)
);

-- II. ACADEMIC STRUCTURE
--    1. Colleges
CREATE TABLE school.colleges (
    college_code                      VARCHAR(10)                   NOT NULL
    , college_name                    VARCHAR(100)                  NOT NULL
    , PRIMARY KEY (college_code)
);

--    2. Courses
CREATE TABLE school.courses (
    course_code                       VARCHAR(10)                   NOT NULL
    , course_name                     VARCHAR(100)                  NOT NULL
    , course_tier                     school.education_level_enum   NOT NULL
    , college_code                    VARCHAR(10)                   NOT NULL
    , PRIMARY KEY (course_code)
);

--    3. Blocks
CREATE TABLE school.blocks (
    block_no                          BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , course_code                     VARCHAR(10)                   NOT NULL
    , year_level                      BIGINT                        NOT NULL
    , block_number                    BIGINT                        NOT NULL
    , PRIMARY KEY (block_no)
);

--    4. Course Subjects
CREATE TABLE school.course_subjects (
    course_code                       VARCHAR(10)                   NOT NULL
    , subject_code                    VARCHAR(10)                   NOT NULL
    , PRIMARY KEY (course_code, subject_code)
);

-- III. ACADEMIC OFFERINGS
--    1. Subjects
CREATE TABLE school.subjects (
    subject_code                      VARCHAR(10)                   NOT NULL
    , subject_name                    VARCHAR(100)                  NOT NULL
    , lec_units                       BIGINT                        NOT NULL DEFAULT 0
    , lab_units                       BIGINT                        NOT NULL DEFAULT 0
    , PRIMARY KEY (subject_code)
);

--    2. Subject Prereqs
CREATE TABLE school.subject_prereqs (
    subject_code                      VARCHAR(10)                   NOT NULL
    , prereq_subject_code             VARCHAR(10)                   NOT NULL
    , PRIMARY KEY (subject_code, prereq_subject_code)
);

--    3. Sections
CREATE TABLE school.sections (
    section_no                        BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , available_slots                 BIGINT                        NOT NULL DEFAULT 40
    , version                         BIGINT                        NOT NULL DEFAULT 0
    , delivery_mode                   school.delivery_mode_enum     NOT NULL
    , subject_code                    VARCHAR(10)                   NOT NULL
    , professor_id                    VARCHAR(10)                   NOT NULL
    , academic_term_no                BIGINT                        NOT NULL
    , PRIMARY KEY (section_no)
);

--    4. Section Blocks
CREATE TABLE school.section_blocks (
    section_no                        BIGINT                        NOT NULL
    , block_no                        BIGINT                        NOT NULL
    , PRIMARY KEY (section_no, block_no)
);

-- IV. ENROLLMENT
--    1. Enrollments
CREATE TABLE school.enrollments (
    enrollment_no                     BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , enrolled_at                     TIMESTAMPTZ                   NOT NULL
    , created_at                      TIMESTAMPTZ                   NOT NULL
    , enrollment_status               school.enrollment_status_enum NOT NULL
    , account_id                      UUID                          NOT NULL
    , academic_term_no                BIGINT                        NOT NULL
    , PRIMARY KEY (enrollment_no)
);

--    2. Enrolled Sections
CREATE TABLE school.enrollment_sections (
    enrollment_no                     BIGINT                        NOT NULL
    , section_no                      BIGINT                        NOT NULL
    , subject_status                  school.subject_status_enum    NOT NULL
    , PRIMARY KEY (enrollment_no, section_no)
);

-- V. TIME & LOCATION
--    1. Schedules
CREATE TABLE school.schedules (
    schedule_no                       BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , day_name                        school.day_name_enum          NOT NULL
    , start_time                      TIME                          NOT NULL
    , end_time                        TIME                          NOT NULL
    , section_no                      BIGINT                        NOT NULL
    , room_no                         BIGINT                        NOT NULL
    , PRIMARY KEY (schedule_no)
);

--    2. Service Histories
CREATE TABLE school.service_histories (
    serv_history_no                   BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , start_date                      DATE                          NOT NULL
    , end_date                        DATE                              NULL
    , serv_status_during              school.service_status_enum    NOT NULL
    , account_id                      UUID                          NOT NULL
    , PRIMARY KEY (serv_history_no)
);

--    3. School Years
CREATE TABLE school.school_years (
    sy_no                             BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , sy_name                         VARCHAR(50)                   NOT NULL
    , sy_start_date                   DATE                          NOT NULL
    , sy_end_date                     DATE                          NOT NULL
    , PRIMARY KEY (sy_no)
);

--    4. Term Types
CREATE TABLE school.term_types (
    term_type_id                      VARCHAR(2)                    NOT NULL
    , term_name                       VARCHAR(50)                   NOT NULL
    , PRIMARY KEY (term_type_id)
);

--    5. Academic Terms
CREATE TABLE school.academic_terms (
    academic_term_no                  BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , term_name                       VARCHAR(50)                   NOT NULL
    , term_start_date                 DATE                          NOT NULL
    , term_end_date                   DATE                          NOT NULL
    , enrollment_start_date           DATE                          NOT NULL
    , enrollment_end_date             DATE                          NOT NULL
    , sy_no                           BIGINT                        NOT NULL
    , term_type_id                    VARCHAR(2)                    NOT NULL
    , PRIMARY KEY (academic_term_no)
);

--    6. Buildings
CREATE TABLE school.buildings (
    building_no                       BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , building_name                   VARCHAR(100)                  NOT NULL
    , PRIMARY KEY (building_no)
);

--    7. Rooms
CREATE TABLE school.rooms (
    room_no                           BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , room_name                       VARCHAR(50)                   NOT NULL
    , room_capacity                   BIGINT                            NULL
    , room_type                       school.room_type_enum         NOT NULL
    , building_no                     BIGINT                            NULL
    , PRIMARY KEY (room_no)
);

-- VI. GRADING
--    1. Grade Components
CREATE TABLE school.grade_components (
    gc_no                            BIGINT                        NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , gc_name                        VARCHAR(100)                  NOT NULL
    , max_score                      BIGINT                        NOT NULL
    , percent                        BIGINT                        NOT NULL
    , section_no                     BIGINT                        NOT NULL
    , parent_gc                      BIGINT                            NULL
    , PRIMARY KEY (gc_no)
);

--    2. Grades
CREATE TABLE school.grades (
    gc_no                            BIGINT                        NOT NULL
    , enrollment_no                  BIGINT                        NOT NULL
    , raw_score                      BIGINT                        NOT NULL
    , PRIMARY KEY (gc_no, enrollment_no)
);

-- =============================================================================
-- CONSTRAINTS
-- =============================================================================

-- I. USER MANAGEMENT
ALTER TABLE school.accounts
    ADD CONSTRAINT email_unique_ck
        UNIQUE (email),
    ADD CONSTRAINT acc_email_fmt_ck
        CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    ADD CONSTRAINT email_lower_ck
        CHECK (email = LOWER(email));

ALTER TABLE school.user_profiles
    ADD CONSTRAINT fk_user_profiles_account
        FOREIGN KEY (account_id)
            REFERENCES school.accounts(account_id)
            ON DELETE CASCADE;

ALTER TABLE school.roles
    ADD CONSTRAINT uq_roles_role_name
        UNIQUE (role_name);

ALTER TABLE school.account_roles
    ADD CONSTRAINT fk_account_roles_account
        FOREIGN KEY (account_id)
            REFERENCES school.accounts(account_id)
            ON DELETE CASCADE,
    ADD CONSTRAINT fk_account_roles_role
        FOREIGN KEY (role_no)
            REFERENCES school.roles(role_no)
            ON DELETE CASCADE;

ALTER TABLE school.students
    ADD CONSTRAINT fk_students_account
        FOREIGN KEY (account_id)
            REFERENCES school.accounts(account_id)
            ON DELETE CASCADE,
    ADD CONSTRAINT uq_students_student_no
        UNIQUE (student_no);

ALTER TABLE school.professors
    ADD CONSTRAINT fk_professors_account
        FOREIGN KEY (account_id)
            REFERENCES school.accounts(account_id)
            ON DELETE CASCADE,
    ADD CONSTRAINT uq_professors_professor_id
        UNIQUE (professor_id);

-- II. ACADEMIC STRUCTURE
ALTER TABLE school.courses
    ADD CONSTRAINT fk_courses_college
        FOREIGN KEY (college_code)
            REFERENCES school.colleges(college_code);

ALTER TABLE school.blocks
    ADD CONSTRAINT fk_blocks_course
        FOREIGN KEY (course_code)
            REFERENCES school.courses(course_code),
    ADD CONSTRAINT chk_blocks_positive
        CHECK (year_level >= 1 AND block_number >= 1);

ALTER TABLE school.course_subjects
    ADD CONSTRAINT fk_cs_course
        FOREIGN KEY (course_code)
            REFERENCES school.courses(course_code)
            ON DELETE CASCADE,
    ADD CONSTRAINT fk_cs_subject
        FOREIGN KEY (subject_code)
            REFERENCES school.subjects(subject_code)
            ON DELETE CASCADE;

-- III. ACADEMIC OFFERINGS
ALTER TABLE school.subjects
    ADD CONSTRAINT chk_subject_units_nonnegative
        CHECK (lec_units >= 0 AND lab_units >= 0);

ALTER TABLE school.subject_prereqs
    ADD CONSTRAINT fk_prereq_subject
        FOREIGN KEY (subject_code)
            REFERENCES school.subjects(subject_code)
            ON DELETE CASCADE,
    ADD CONSTRAINT fk_prereq_required
        FOREIGN KEY (prereq_subject_code)
            REFERENCES school.subjects(subject_code)
            ON DELETE CASCADE;

ALTER TABLE school.sections
    ADD CONSTRAINT fk_sections_subject
        FOREIGN KEY (subject_code)
            REFERENCES school.subjects(subject_code),
    ADD CONSTRAINT fk_sections_professor
        FOREIGN KEY (professor_id)
            REFERENCES school.professors(professor_id)
            ON UPDATE CASCADE,
    ADD CONSTRAINT fk_sections_term
        FOREIGN KEY (academic_term_no)
            REFERENCES school.academic_terms(academic_term_no),
    ADD CONSTRAINT chk_section_slots
        CHECK (available_slots > 0);

ALTER TABLE school.section_blocks
    ADD CONSTRAINT fk_sb_section
        FOREIGN KEY (section_no)
            REFERENCES school.sections(section_no)
            ON DELETE CASCADE,
    ADD CONSTRAINT fk_sb_block
        FOREIGN KEY (block_no)
            REFERENCES school.blocks(block_no)
            ON DELETE CASCADE;

-- IV. ENROLLMENT
ALTER TABLE school.enrollments
    ADD CONSTRAINT fk_enrollments_account
        FOREIGN KEY (account_id)
            REFERENCES school.accounts(account_id),
    ADD CONSTRAINT fk_enrollments_term
        FOREIGN KEY (academic_term_no)
            REFERENCES school.academic_terms(academic_term_no);

ALTER TABLE school.enrollment_sections
    ADD CONSTRAINT fk_es_enrollment
        FOREIGN KEY (enrollment_no)
            REFERENCES school.enrollments(enrollment_no)
            ON DELETE CASCADE,
    ADD CONSTRAINT fk_es_section
        FOREIGN KEY (section_no)
            REFERENCES school.sections(section_no);

-- V. TIME & LOCATION
ALTER TABLE school.schedules
    ADD CONSTRAINT fk_schedules_section
        FOREIGN KEY (section_no)
            REFERENCES school.sections(section_no)
            ON DELETE CASCADE,
    ADD CONSTRAINT fk_schedules_room
        FOREIGN KEY (room_no)
            REFERENCES school.rooms(room_no)
            ON DELETE SET NULL,
    ADD CONSTRAINT chk_schedule_time
        CHECK (start_time < end_time),
    ADD CONSTRAINT no_room_overlap
        EXCLUDE USING GIST (
        room_no WITH =,
        day_name WITH =,
        tsrange(
                ('2000-01-01 ' || start_time)::timestamp,
                ('2000-01-01 ' || end_time)::timestamp
        ) WITH &&
        ) WHERE (room_no IS NOT NULL);

ALTER TABLE school.service_histories
    ADD CONSTRAINT fk_sh_account
        FOREIGN KEY (account_id)
            REFERENCES school.accounts(account_id)
            ON DELETE CASCADE;

ALTER TABLE school.academic_terms
    ADD CONSTRAINT fk_at_sy
        FOREIGN KEY (sy_no)
            REFERENCES school.school_years(sy_no),
    ADD CONSTRAINT fk_at_type
        FOREIGN KEY (term_type_id)
            REFERENCES school.term_types(term_type_id),
    ADD CONSTRAINT chk_term_dates
        CHECK (
            term_start_date < term_end_date
                AND enrollment_start_date <= enrollment_end_date
            );

ALTER TABLE school.rooms
    ADD CONSTRAINT chk_room_capacity
        CHECK (room_capacity IS NULL OR room_capacity > 0);

-- VI. GRADING
ALTER TABLE school.grade_components
    ADD CONSTRAINT fk_gc_section
        FOREIGN KEY (section_no)
            REFERENCES school.sections(section_no)
            ON DELETE CASCADE,
    ADD CONSTRAINT fk_gc_parent
        FOREIGN KEY (parent_gc)
            REFERENCES school.grade_components(gc_no)
            ON DELETE SET NULL,
    ADD CONSTRAINT chk_gc_percent
        CHECK (percent BETWEEN 0 AND 100),
    ADD CONSTRAINT chk_gc_values
        CHECK (max_score > 0 AND percent > 0 AND percent <= 100);

ALTER TABLE school.grades
    ADD CONSTRAINT fk_grades_gc
        FOREIGN KEY (gc_no)
            REFERENCES school.grade_components(gc_no)
            ON DELETE CASCADE,
    ADD CONSTRAINT fk_grades_enrollment
        FOREIGN KEY (enrollment_no)
            REFERENCES school.enrollments(enrollment_no)
            ON DELETE CASCADE;

-- =============================================================================
-- VIEW DEFINITIONS
-- =============================================================================
CREATE OR REPLACE VIEW school.vwlogin AS
SELECT
    a.account_id,
    a.email,
    a.password_hash,
    a.status,
    ar.role_no
FROM
    school.accounts a
        JOIN
    school.account_roles ar
    ON a.account_id = ar.account_id;

-- =============================================================================
-- DEFAULT INSERTS
-- =============================================================================
INSERT INTO school.roles (role_name) VALUES ('STUDENT'), ('PROFESSOR'), ('ADMIN');
INSERT INTO school.buildings (building_name) VALUES ('University Grounds'), ('Virtual Campus');
INSERT INTO school.rooms (room_name, room_capacity, room_type, building_no) VALUES ('FIELD', NULL, 'FIELD', 1);
INSERT INTO school.rooms (room_name, room_capacity, room_type, building_no) VALUES ('MS TEAMS', NULL, 'ONLINE', 2);

-- =============================================================================
-- TRIGGERS (DATA INTEGRITY)
-- =============================================================================

-- 1. GRADE PERCENTAGE LIMIT (Cannot Exceed 100%)
CREATE OR REPLACE FUNCTION school.check_grade_percentage_limit()
    RETURNS TRIGGER AS $$
DECLARE
    existing_sum INTEGER;
    new_total INTEGER;
BEGIN
    IF NEW.parent_gc IS NULL THEN
        SELECT COALESCE(SUM(percent), 0)
        INTO existing_sum
        FROM school.grade_components
        WHERE section_no = NEW.section_no
          AND parent_gc IS NULL
          AND gc_no IS DISTINCT FROM NEW.gc_no;

        new_total := existing_sum + NEW.percent;

        IF new_total > 100 THEN
            RAISE EXCEPTION 'Grade Component Violation: Section % total would be % (Limit 100)', NEW.section_no, new_total;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_enforce_max_percent ON school.grade_components;

CREATE TRIGGER trg_enforce_max_percent
    BEFORE INSERT OR UPDATE ON school.grade_components
    FOR EACH ROW
EXECUTE FUNCTION school.check_grade_percentage_limit();

-- 2. PROFESSOR CLONING CHECK (Overlap Prevention)
CREATE OR REPLACE FUNCTION school.check_professor_schedule_conflict()
    RETURNS TRIGGER AS $$
DECLARE
    current_prof_id VARCHAR;
    conflict_data RECORD;
BEGIN
    SELECT professor_id
    INTO current_prof_id
    FROM school.sections
    WHERE section_no = NEW.section_no;

    SELECT s.section_no, s.start_time, s.end_time
    INTO conflict_data
    FROM school.schedules s
             JOIN school.sections sec ON s.section_no = sec.section_no
    WHERE sec.professor_id = current_prof_id
      AND s.day_name = NEW.day_name
      AND s.schedule_no IS DISTINCT FROM NEW.schedule_no
      AND (NEW.start_time < s.end_time AND NEW.end_time > s.start_time)
    LIMIT 1;

    IF FOUND THEN
        RAISE EXCEPTION 'Professor Conflict: % is busy at this time in section %.', current_prof_id, conflict_data.section_no;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_prevent_prof_cloning ON school.schedules;

CREATE TRIGGER trg_prevent_prof_cloning
    BEFORE INSERT OR UPDATE ON school.schedules
    FOR EACH ROW
EXECUTE FUNCTION school.check_professor_schedule_conflict();

-- 3. GRADE SCORE LIMIT CHECK
CREATE OR REPLACE FUNCTION school.check_grade_score_limit()
    RETURNS TRIGGER AS $$
DECLARE
    allowed_max BIGINT;
BEGIN
    SELECT max_score
    INTO allowed_max
    FROM school.grade_components
    WHERE gc_no = NEW.gc_no;

    IF NEW.raw_score < 0 THEN
        RAISE EXCEPTION 'Score Violation: Raw score % cannot be negative.', NEW.raw_score;
    END IF;

    IF NEW.raw_score > allowed_max THEN
        RAISE EXCEPTION 'Score Violation: Raw score % exceeds max score % for this component.', NEW.raw_score, allowed_max;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_grade_score ON school.grades;

CREATE TRIGGER trg_check_grade_score
    BEFORE INSERT OR UPDATE ON school.grades
    FOR EACH ROW
EXECUTE FUNCTION school.check_grade_score_limit();

-- 4. GRADE COMPONENT PARENT SECTION CHECK
CREATE OR REPLACE FUNCTION school.check_gc_parent_match()
    RETURNS TRIGGER AS $$
DECLARE
    parent_section BIGINT;
BEGIN
    IF NEW.parent_gc IS NOT NULL THEN
        SELECT section_no
        INTO parent_section
        FROM school.grade_components
        WHERE gc_no = NEW.parent_gc;

        IF parent_section != NEW.section_no THEN
            RAISE EXCEPTION 'Hierarchy Error: Child component must belong to the same section as the parent component.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_gc_parent ON school.grade_components;

CREATE TRIGGER trg_check_gc_parent
    BEFORE INSERT OR UPDATE ON school.grade_components
    FOR EACH ROW
EXECUTE FUNCTION school.check_gc_parent_match();

-- =============================================================================
-- INITIALIZE ADMIN ACCOUNT
-- =============================================================================
WITH acc AS (
    INSERT INTO school.accounts (email, password_hash)
        VALUES ('admin@plm.edu.ph', '$2a$10$urO3DSWyBBPEYuh8GQzXPu4KFlksPbWsc.pnRWY6Z0vTA.jsMWTkO')
        RETURNING account_id
),
     profile AS (
         INSERT INTO school.user_profiles (account_id, first_name, last_name)
             SELECT account_id, 'Admin', 'User'
             FROM acc
             RETURNING account_id
     )
INSERT INTO school.account_roles (account_id, role_no)
SELECT account_id, 3  -- ADMIN
FROM profile;